runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# env_variables:
#   GCS_AUTH_FILE: auth.json

health_check:
  enable_health_check: False

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

endpoints_api_service:
  name: https://makusmart-analytics.uc.r.appspot.com
  rollout_strategy: managed