swagger: '2.0'
info:
  description: API Test for Cloud Endpoints
  title: API test Cloud Endpoints
  version: 1.0.0
host: makusmart-analytics.appspot.com
schemes: [http]
produces: [application/json]
paths:
  /readiness_check:
    get:
      summary: 'Tells GCP that the app is ready'
      responses:
        default:
          description: Default response.
      parameters: []
      operationId: readiness_check