swagger: '2.0'
info:
  description: API Test for Cloud Endpoints
  title: API test Cloud Endpoints
  version: 1.0.0
host: makusmart-analytics.uc.r.appspot.com
schemes: [http]
produces: [application/json]
paths:
  /readiness_check:
    get:
      summary: ''
      responses:
        default:
          description: Default response.
      parameters: []
      tags:
      operationId: readiness_check

  /liveness_check:
    get:
      summary: ''
      responses:
        default:
          description: Default response.
      parameters: []
      tags:
      operationId: liveness_check